movies/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from movies.views import list_of_movies, movie_detail, add_movie_to_group

urlpatterns = [
    path(
        'list_movies/',
        list_of_movies,
        name='movies'
    ),
    path(
        'details/<int:movie_id>/',
        movie_detail,
        name='movie_details'
    ),
    path(
        'movies/<int:movie_id>/add_to_group/',
        login_required(add_movie_to_group),
        name='add_movie_to_group'
    ),
]

moviestar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('movies/', include('movies.urls')),
    path('groups/', include('review_groups.urls')),
    path('users/', include('accounts.urls')),
    path(
        'reviews/',
        include(('reviews.urls', 'reviews'), namespace='reviews')
    ), ]

handler404 = 'moviestar.views.handler404'

review_groups/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from moviestar.views import access_denied
from review_groups.views import (
    list_of_groups,
    group_details,
    create_groups,
    edit_group,
    delete_group,
    movie_review,
    join_leave_group
)

urlpatterns = [
    path(
        'list_groups/',
        list_of_groups,
        name='list_of_groups'
    ),
    path(
        'details/<int:group_id>/',
        login_required(group_details),
        name='group_details'
    ),
    path(
        'create/',
        login_required(create_groups),
        name='create_groups'
    ),
    path(
        '<int:group_id>/edit/',
        login_required(edit_group),
        name='edit_group'
    ),
    path(
        '<int:group_id>/delete/',
        login_required(delete_group),
        name='delete_group'
    ),
    path(
        '<int:group_id>/<int:movie_id>/reviews',
        login_required(movie_review),
        name='movie_review'
    ),
    path(
        '<int:group_id>/join_leave/',
        login_required(join_leave_group),
        name='join_leave_group'
    ),
    path(
        'access_denied/',
        access_denied,
        name='access_denied'
    )
]

reviews/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from moviestar.views import access_denied
from .views import submit_review, edit_review, delete_review

urlpatterns = [
    path(
        '<int:group_id>/<int:movie_id>/reviews/',
        login_required(submit_review),
        name='submit_review'
    ),
    path(
        '<int:group_id>/<int:movie_id>/<int:review_id>/edit_review',
        login_required(edit_review),
        name='edit_review'
    ),
    path(
        '<int:group_id>/<int:movie_id>/<int:review_id>/delete_review',
        login_required(delete_review),
        name='delete_review'
    ),
    path(
        'access_denied/',
        access_denied,
        name='access_denied'
    ),
]

review_groups/models.py
from django.db import models
from accounts.models import CustomUser
from movies.models import MovieDetails

# Create your models here.


class ReviewGroups(models.Model):
    """
    Represents a review group for movies.

    Each group has a unique identifier (group_id)
      and is associated with a name (group_name).
    A group can have a description (group_description)
      providing additional information.
    It includes a ManyToMany relationship with movies (group_movies)
      and users (group_members).
    The creator of the group is tracked through the
      ForeignKey relationship (group_creator).

    Methods:
        - __str__: Returns the group_name for a
                   human-readable representation.
    """
    group_id = models.AutoField(
        primary_key=True
    )
    group_name = models.CharField(
        max_length=120,
        unique=True,
        blank=False,
        null=False
    )
    group_description = models.TextField(
        max_length=500,
        blank=True,
        null=True
    )
    group_movies = models.ManyToManyField(
        MovieDetails
    )
    group_members = models.ManyToManyField(
        CustomUser,
        related_name='user_groups_membership'
    )
    group_creator = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='created_groups',
        null=True,
        blank=True
    )

    def __str__(self):
        return self.group_name

review_groups/forms.py
from django import forms
from .models import ReviewGroups


class ReviewGroupsForm(forms.ModelForm):
    """
    Form for creating or updating a review group.

    This form is based on the ReviewGroups model and includes fields
      for group_name and group_description.

    Attributes:
        - model: The associated ReviewGroups model.
        - fields: The fields to be included in the form.
    """
    class Meta:
        model = ReviewGroups
        fields = ['group_name', 'group_description']

        labels = {
            'group_name': 'Group Name',
            'group_description': 'Group Description',
        }

        widgets = {
            'group_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter A Group Name'
                    }
                ),
            'group_description': forms.Textarea(
                attrs={
                    'placeholder': 'Enter A Group Description',
                    'rows': 10,
                    'cols': 35
                    }
                ),
        }

review_groups/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from .models import ReviewGroups
from movies.models import MovieDetails
from .forms import ReviewGroupsForm
from reviews.forms import ReviewForm
from reviews.views import get_movie_reviews


def list_of_groups(request):
    """
    Renders a list of all review groups available in the database.

    Retrieves all review groups from the database
      and passes them to the template for rendering.

    Args:
        - request (HttpRequest): The HTTP request object.

    Returns:
        - HttpResponse: Rendered HTML page
          displaying the list of review groups.

    Template:
        - 'review_groups/display_groups.html'
    """
    groups = ReviewGroups.objects.all()

    return render(
        request,
        'review_groups/display_groups.html',
        {'groups': groups}
    )


@login_required
def group_details(request, group_id):
    """
    Renders the details of a specific group.

    Retrieves the details of a group
      with the given 'group_id' from the database.
    Renders the group details in the
      'review_groups/group_details.html' template.

    Args:
        - request (HttpRequest): The HTTP request object.
        - group_id (int): The unique identifier of the review group.

    Returns:
        - HttpResponse: Rendered HTML page
          displaying the details of the review group.

    Template:
        - 'review_groups/group_details.html'

    Raises:
        - Http404: If no review group is found with the specified 'group_id'.
    """
    group = get_object_or_404(ReviewGroups, group_id=group_id)

    return render(
        request,
        'review_groups/group_details.html',
        {'group': group, 'back_url': reverse('list_of_groups')}
    )


@login_required
def create_groups(request):
    """
    Handles the creation of review groups.

    If the HTTP request method is POST, validates the submitted form data.
    If the form is valid, sets the group creator to the logged-in user,
      saves the review group, and redirects to the 'list_of_groups' view.
    If the HTTP request method is GET, renders the
      'review_groups/create_groups.html' template
    with an empty form for creating a new review group.

    Args:
        - request (HttpRequest): The HTTP request object.

    Returns:
        - HttpResponse: Rendered HTML page displaying
          the form for creating a review group.

    Template:
        - 'review_groups/create_groups.html'

    Redirects:
        - To the 'list_of_groups' view upon
          successful creation of a review group.
    """
    if request.method == 'POST':
        form = ReviewGroupsForm(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            group.group_creator = request.user
            group.save()

            group.group_members.add(request.user)

            messages.success(
                request,
                'Group created'
            )

            return redirect('list_of_groups')
    else:
        form = ReviewGroupsForm()

    return render(
        request,
        'review_groups/create_groups.html',
        {'form': form, 'back_url': reverse('list_of_groups')}
    )


@login_required
def edit_group(request, group_id):
    """
    Handles the editing of review groups.

    If the form is valid, saves the review group and
      redirects to the 'group_details' view.
    If the HTTP request method is GET,
      renders the 'review_groups/edit_group.html' template
    with the form pre-filled with the current group details for editing.
    If the HTTP request method is POST, validates the submitted form data.

    Args:
        - request (HttpRequest): The HTTP request object.

    Returns:
        - HttpResponse:
          Rendered HTML page displaying the form for editing a review group.

    Template:
        - 'review_groups/edit_group.html'

    Redirects:
        - To the 'group_details' view upon successful editing
          of a review group.
    """
    group = get_object_or_404(ReviewGroups, group_id=group_id)

    if request.user == group.group_creator:
        if request.method == 'POST':
            form = ReviewGroupsForm(request.POST, instance=group)
            if form.is_valid():
                form.save()

                messages.success(
                    request,
                    'Group edited'
                )

                return redirect('group_details', group_id=group_id)
        else:
            form = ReviewGroupsForm(instance=group)

        return render(
            request,
            'review_groups/edit_group.html',
            {'form': form, 'group': group}
        )
    else:
        return redirect('access_denied')


@login_required
def delete_group(request, group_id):
    """
    Handles the deletion of review groups.

    If the HTTP request method is GET and the logged-in user
      is the creator of the group,
    renders the 'review_groups/delete_group.html'
      template to confirm the deletion.
    If the HTTP request method is POST and the logged-in user
      is the creator of the group,
    deletes the review group and redirects to the 'list_of_groups' view.

    Args:
        - request (HttpRequest): The HTTP request object.
        - group_id (int): The ID of the group to be deleted.

    Returns:
        - HttpResponse: Rendered HTML page for confirming
          the deletion of a review group.

    Template:
        - 'review_groups/delete_group.html'

    Redirects:
        - To the 'list_of_groups' view upon successful deletion
          of a review group.
    """
    group = get_object_or_404(ReviewGroups, group_id=group_id)

    if request.user == group.group_creator:
        if request.method == 'POST':
            group.delete()

            messages.success(
                request,
                'Group deleted'
            )

            return redirect('list_of_groups')

        return render(
            request,
            'review_groups/delete_group.html',
            {'group': group}
        )
    else:
        return render(request, 'review_groups/access_denied.html')


@login_required
def movie_review(request, group_id, movie_id):
    """
    Displays details for a specific movie within a review group.

    Retrieves details for the specified movie using its ID.
    Fetches a list of all available review groups.

    Parameters:
        - request: HttpRequest object.
        - group_id: Integer, ID of the review group.
        - movie_id: Integer, ID of the movie to display details for.

    Returns:
        - Rendered HTML page with movie details
          within the context of a review group.
    """
    group = get_object_or_404(ReviewGroups, group_id=group_id)

    if request.user in group.group_members.all():
        review_group = get_object_or_404(ReviewGroups, group_id=group_id)
        movie = get_object_or_404(MovieDetails, movie_id=movie_id)
        group_name = review_group.group_name

        reviews = get_movie_reviews(group_id, movie_id)

        back_url = reverse('group_details', kwargs={'group_id': group_id})

        context = {
            'group': review_group,
            'movie': movie,
            'group_name': group_name,
            'reviews': reviews,
            'back_url': back_url,
            'form': ReviewForm(),
        }

        return render(
            request,
            'review_groups/movie_review_in_group.html',
            context
        )
    else:
        return redirect('access_denied')


@login_required
def join_leave_group(request, group_id):
    """
    Handles the user's request to join or leave a review group.

    Retrieves the specified review group using its ID.
    Checks if the requesting user is already a member of the group.
    If the user is a member, and they are not the group admin,
      removes them from the group;
    If the user is the group admin and decides to leave,
      redirects to the 'delete_group' view for group deletion.

    Parameters:
        - request: HttpRequest object.
        - group_id: Integer, ID of the review group to join or leave.

    Returns:
        - Redirects to the 'group_details' page for the
          specified review group after the join/leave action.
    """
    group = ReviewGroups.objects.get(pk=group_id)

    if request.user == group.group_creator:

        messages.success(
            request,
            'As the group administrator, '
            'you must delete the group in order to leave.'
        )

        return redirect('delete_group', group_id=group_id)
    elif request.user in group.group_members.all():

        messages.success(
            request,
            'You left the group'
        )

        group.group_members.remove(request.user)
    else:

        messages.success(
            request,
            'You joined the group'
        )

        group.group_members.add(request.user)

    return redirect('group_details', group_id=group_id)

review_groups/templates/review_groups/create_groups.html
{% extends 'base.html' %}

{% block title %}Create groups{% endblock %}

{% block content %}

<!-- create group -->
<div class="container mt-4">
    <h1 class="text-left display-4 mb-4">Create a new Group</h1>

    <!-- create group form -->
    <form method="post" action="{% url 'create_groups' %}">
        {% csrf_token %}

        <div class="form-group row">
            <label for="{{ form.group_name.id_for_label }}" class="col-sm-2 col-form-label">Group Name:</label>
            <div class="col-sm-10">
                {{ form.group_name }}
                {{ form.group_name.errors }}
            </div>
        </div>

        <div class="form-group row">
            <label for="{{ form.group_description.id_for_label }}" class="col-sm-2 col-form-label">Group
                Description:</label>
            <div class="col-sm-10">
                {{ form.group_description }}
                {{ form.group_description.errors }}
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-10 offset-sm-2">
                <button type="submit" class="btn btn-primary">Create Group</button>
            </div>
        </div>
    </form>
    <!-- end create group form -->

    <!-- back to display_gtoups -->
    <a href="{{ back_url }}" class="btn btn-secondary mt-3">Back to all Groups</a>
    <!-- end back to display_gtoups -->

</div>
<!-- end create group -->
{% endblock %}

review_groups/templates/review_groups/delete_group.html
{% extends 'base.html' %}

{% block title %}Delete groups{% endblock %}

{% block content %}

<!-- delete group -->
<div class="container mt-4">
    <h1 class="text-left display-4 mb-4">Delete Group</h1>

    <p>Are you sure you want to delete the group <strong>{{ group.group_name }}</strong>?</p>
    <p>This group and its content will be deleted <strong><u>forever</u></strong> and can't be brought back!</p>

    <!-- delete group button -->
    <form method="post" action="{% url 'delete_group' group.group_id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete!</button>
    </form>
    <!-- end delete group button -->

    <!-- back to group with id -->
    <a href="{% url 'group_details' group.group_id %}" class="btn btn-secondary mt-3">Cancel</a>
    <!-- end delete group -->

</div>
<!-- end delete group -->

{% endblock %}

review_groups/templates/review_groups/display_groups.html
{% extends 'base.html' %}

{% block title %}Display all groups{% endblock %}

{% block content %}

<!-- list of groups -->
<div class="container mt-4">
    <h1 class="text-left display-4 mb-4">List of Groups</h1>

    {% if groups %}
    <div class="list-group">
        {% for group in groups %}
        <div class="list-group-item mb-4 border rounded py-4">
            <a href="{% url 'group_details' group.group_id %}" class="text-decoration-none">
                <h2 class="h4 mb-0">{{ group.group_name }}</h2>
            </a>
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <!-- Add "Create Group" button -->
    <div class="text-center mt-4">
        <a href="{% url 'create_groups' %}" class="btn btn-primary">Create Group</a>
    </div>
</div>
<!-- end list of groups -->

{% endblock %}

review_groups/templates/review_groups/edit_group.html
{% extends 'base.html' %}

{% block title %}Edit groups{% endblock %}

{% block content %}

<!-- edit group -->
<div class="container mt-4">
    <h1 class="text-left display-4 mb-4">Edit Group</h1>

    <!-- edit group form -->
    <form method="post" action="{% url 'edit_group' group.group_id %}">
        {% csrf_token %}

        <div class="form-group row">
            <label for="{{ form.group_name.id_for_label }}" class="col-sm-2 col-form-label">Group Name:</label>
            <div class="col-sm-10">
                {{ form.group_name }}
                {{ form.group_name.errors }}
            </div>
        </div>

        <div class="form-group row">
            <label for="{{ form.group_description.id_for_label }}" class="col-sm-2 col-form-label">Group
                Description:</label>
            <div class="col-sm-10">
                {{ form.group_description }}
                {{ form.group_description.errors }}
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
    <!-- end edit group form -->

    <!-- back to list of groups button -->
    <a href="{% url 'list_of_groups' %}" class="btn btn-secondary mt-3">Cancel</a>
    <!-- end back to list of groups button -->

</div>
<!-- end edit group -->

{% endblock %}

review_groups/templates/review_groups/group_details.html
{% extends 'base.html' %}

{% block title %}Group details{% endblock %}

{% block content %}

<!-- group details -->
<div class="container mt-4">
    <h1 class="text-left display-4 mb-4">{{ group.group_name }}</h1>

    <div class="group-info mb-4">
        <p>{{ group.group_description }}</p>
    </div>

    <h2 class="text-left display-6">Group Movies</h2>
    <p class="subtle-italic">Click on a movie to see or write a review.</p>

    <!-- separate movie details for groups -->
    <div class="row mb-4">
        {% for movie in group.group_movies.all %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4">
            <div class="card h-100 bg-dark">
                <a href="{% url 'movie_review' group_id=group.group_id movie_id=movie.movie_id %}"
                    class="d-flex flex-column justify-content-between text-white">
                    <div class="card-body-movies p-0 d-flex flex-column align-items-center">
                        {% if movie.movie_poster %}
                        <img src="{{ movie.get_poster_url }}" alt="Movie Poster"
                            class="img-fluid rounded-top rounded-10 mb-3">
                        {% endif %}
                        <span class="d-block w-100 my-3 px-3 text-break">{{ movie.movie_title }}</span>
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- end separate movie details for groups -->

    <h2 class="text-left display-6">Group Admin</h2>
    {% for member in group.group_members.all %}
    {% if member == group.group_creator %}
    <p>{{ member.username }}</p>
    {% endif %}
    {% endfor %}

    <h2 class="text-left display-6">Group Members</h2>
    {% for member in group.group_members.all %}
    <p>{{ member.username }}</p>
    {% endfor %}

    {% if user.is_authenticated and group.group_creator == user %}
    <div class="mt-4 mb-4">
        <a href="{% url 'edit_group' group.group_id %}" class="btn btn-primary mr-2">Edit Group</a>
        <a href="{% url 'delete_group' group.group_id %}" class="btn btn-danger">Delete Group</a>
    </div>
    {% endif %}

    {% if user.is_authenticated %}
    {% if user in group.group_members.all %}
    <form action="{% url 'join_leave_group' group.group_id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Leave Group</button>
    </form>
    {% else %}
    <form action="{% url 'join_leave_group' group.group_id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Join Group</button>
    </form>
    {% endif %}
    {% else %}
    <p>Login to join the group</p>
    {% endif %}

    <!-- back to display_groups button -->
    <a href="{{ back_url }}" class="btn btn-secondary mt-4 mb-4">Back to all Groups</a>
    <!-- end back to display_groups button -->

</div>
<!-- end group details -->

{% endblock %}

review_groups/templates/review_groups/movie_review_in_group.html
{% extends 'base.html' %}

{% block title %}Movie review{% endblock %}

{% block content %}


<!-- movie review in group -->
<div class="container mt-4">

  <!-- display movie to review -->
  <h1 class="text-left display-4 mb-4">{{ movie.movie_title }} - {{ group.group_name }}</h1>

  <div class="row">
    {% if movie.movie_poster %}
    <div class="col-md-4">
      <img src="{{ movie.get_poster_url }}" alt="Movie Poster" class="img-fluid">
    </div>
    {% endif %}

    <div class="col-md-8">
      <p class="lead mb-3">{{ movie.movie_description }}</p>
      <div class="list-unstyled mb-4">
        <div>
          <div class="row">
            <div class="col-md-3"><strong>Genre</strong></div>
            <div class="col-md-9">{{ movie.movie_genre|join:", " }}</div>
          </div>
        </div>
        <div>
          <div class="row">
            <div class="col-md-3"><strong>Release Date</strong></div>
            <div class="col-md-9">{{ movie.movie_release_date }}</div>
          </div>
        </div>
        <div>
        </div>
      </div>
    </div>
  </div>
  <!-- end display movie to review -->

  <!-- displays reviews -->
  <div class="mt-4">
    <h2 class="text-left display-6 mb-4">Reviews</h2>

    {% if reviews %}
    <ul class="list-unstyled">
      {% for review in reviews %}
      <li class="mb-4">
        <div class="card">
          <div class="card-body">
            <p class="card-title"><strong>A review by {{ review.review_user }}</strong></p>
            <p><strong>Rating:</strong> {{ review.review_rating }}</p>
            <p><strong>{{ review.review_title }}</strong></p>
            <p>{{ review.review_text }}</p>
            {% if review.review_user == user %}
            <a href="{% url 'reviews:edit_review' group_id=group.group_id movie_id=movie.movie_id review_id=review.review_id %}"
              class="btn btn-primary btn-sm">Edit</a>
            <a href="{% url 'reviews:delete_review' group_id=group.group_id movie_id=movie.movie_id review_id=review.review_id %}"
              class="btn btn-danger btn-sm">Delete</a>
            {% endif %}
          </div>
        </div>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No reviews available for this movie yet.</p>
    {% endif %}
  </div>
  <!-- end displays reviews -->

  <!-- write a review -->
  <div class="mt-4">
    <h2 class="text-left display-6 mb-4">Submit a Review</h2>

    <!-- write a review form -->
    <form method="post" action="{% url 'reviews:submit_review' group_id=group.group_id movie_id=movie.movie_id %}">
      {% csrf_token %}

      {{ form.non_field_errors }}

      <div class="form-group row">
        <label for="{{ form.review_rating.id_for_label }}"
          class="col-sm-2 col-form-label"><strong>Rating</strong></label>
        <div class="col-sm-10">
          {{ form.review_rating }}
          {{ form.review_rating.errors }}
        </div>
      </div>

      <div class="form-group row">
        <label for="{{ form.review_title.id_for_label }}" class="col-sm-2 col-form-label"><strong>Review
            title</strong></label>
        <div class="col-sm-10">
          {{ form.review_title }}
          {{ form.review_title.errors }}
        </div>
      </div>

      <div class="form-group row">
        <label for="{{ form.review_text.id_for_label }}" class="col-sm-2 col-form-label box-sizing"><strong>Review text</strong></label>
        <div class="col-12 col-sm-10">
            {{ form.review_text }}
            {{ form.review_text.errors }}
        </div>
    </div>

      <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
          <button type="submit" class="btn btn-primary mt-3">Submit Review</button>
        </div>
      </div>
    </form>
    <!-- end write a review form -->
    <!-- end write a review -->

    <!-- back to group_details button -->
    <a href="{{ back_url }}" class="btn btn-secondary mt-3 mb-4">Back to Group</a>
    <!-- end back to group_details button -->

  </div>
</div>
<!-- end movie review in group -->

{% endblock %}